#! /bin/bash

battery_level="$(cat /sys/class/power_supply/BAT0/capacity)"
battery_status=""
battery_icon=""

if [[ "$(cat /sys/class/power_supply/BAT0/status)" == "Charging" ]]; then battery_status=" "; fi
if [ "$battery_status" == "" ]; then
	if [ $battery_level -lt 20 ]; then
		dunstify -u critical "ALERT" "Low Battery"
	fi
fi

if [ $battery_level -lt 25 ]; then
	battery_icon=""
elif [ $battery_level -lt 50 ]; then
	battery_icon=""
elif [ $battery_level -lt 75 ]; then
	battery_icon=""
fi
echo "$battery_icon $battery_level%$battery_status"
