#! /bin/bash

battery_level="$(cat /sys/class/power_supply/BAT0/capacity)"
if [[ "$(cat /sys/class/power_supply/BAT0/status)" == "Charging" ]]; then battery_status="⚡"; fi
if [ "$battery_status" == "" ]; then
	if [ $battery_level -lt 20 ]; then
		dunstify -u critical "ALERT" "Low Battery"
	fi
fi
echo $battery_level% $battery_status
