#! /bin/sh

# pgrep -x sxhkd > /dev/null ||
~/.config/polybar/launch
xsetroot -cursor_name left_ptr
~/.fehbg
picom -c --experimental-backends &
sxhkd &

bspc monitor -g 1024x574+0+26
bspc monitor -d 1 2 3 4 5 6

bspc config border_width         2
bspc config window_gap           8
bspc config top_padding 0
bspc config bottom_padding 0

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config pointer_follows_focus true

bspc rule -a Brave-browser desktop=6 state=fullscreen follow=on focus=on
bspc rule -a Zathura desktop=5 state=fullscreen follow=on focus=on
bspc rule -a Sxiv  state=floating focus=on rectangle=800x556+0+0 center=on
