#! /bin/sh

# pgrep -x sxhkd > /dev/null ||
~/.config/polybar/launch
xsetroot -cursor_name left_ptr
~/.fehbg
picom -c --backend glx &
sxhkd &
dunst &
lxpolkit &
flameshot &

bspc monitor -g 1920x1080+0+0
bspc monitor -d 1 2 3 4 5 6 7 8

bspc config border_width         2
bspc config window_gap           8
bspc config top_padding 35
bspc config bottom_padding 0

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config pointer_follows_focus true

bspc query -N -n .floating | xargs -I {} bspc query -T -n {} | grep -E 'Brave-browser|Zathura' | grep -Eo '"id":[0-9]+' | awk -F: '{print $2}' | xargs -I {} bspc config -n {} border_width 0

bspc rule -a Brave-browser desktop=8 state=floating rectangle=1920x1050+0+30 follow=on focus=on border=off
bspc rule -a Brave  state=floating focus=on rectangle=800x556+0+0 center=on
bspc rule -a Zathura desktop=7 state=floating rectangle=1920x1050+0+30 follow=on focus=on border=off
bspc rule -a Nsxiv  state=floating focus=on rectangle=800x556+0+0 center=on
bspc rule -a Anki desktop=5 follow=on focus=on
bspc rule -a Gsimplecal state=floating rectangle=316x212+1600+37
