cursor #f1dedc
cursor_text_color #d8c2be

foreground            #f1dedc
background            #1a1110
selection_foreground  #442926
selection_background  #e7bdb7
url_color             #ffb4aa

color0   #1a1110
color1   #e04783
color2   #9bd66e
color3   #dba97b
color4   #ca6556
color5   #bf928c
color6   #ffb4aa
color7   #abb2bf
color8   #5c6370
color9   #e05f95
color10  #ade086
color11  #e8be97
color12  #ffc0b6
color13  #bc5c5f
color14  #a26b58
color15  #ffffff
